/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qibaike.thriftnameserver.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum State implements org.apache.thrift.TEnum {
  UP(1),
  DOWN(2),
  Tombstone(3),
  Joining(4),
  Leaving(5),
  DOWN_1(6),
  DOWN_2(7);

  private final int value;

  private State(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static State findByValue(int value) { 
    switch (value) {
      case 1:
        return UP;
      case 2:
        return DOWN;
      case 3:
        return Tombstone;
      case 4:
        return Joining;
      case 5:
        return Leaving;
      case 6:
        return DOWN_1;
      case 7:
        return DOWN_2;
      default:
        return null;
    }
  }
}
