/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qibaike.tns.protocol.rpc.event;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 操作
 * 
 */
public enum Operation implements org.apache.thrift.TEnum {
  SYNC_CLUSTER(1),
  SYNC_SERVICE(2),
  PING_SERVICE(3),
  SYNC_CAS(4),
  TAKE_LEVENT(5);

  private final int value;

  private Operation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Operation findByValue(int value) { 
    switch (value) {
      case 1:
        return SYNC_CLUSTER;
      case 2:
        return SYNC_SERVICE;
      case 3:
        return PING_SERVICE;
      case 4:
        return SYNC_CAS;
      case 5:
        return TAKE_LEVENT;
      default:
        return null;
    }
  }
}
